#import "@preview/starter-journal-article:0.4.0": article, author-meta

#show link: underline
#set highlight(fill: luma(230), radius: 2pt, bottom-edge: -2pt, top-edge: "ascender")
#set page(numbering: "1")
#set heading(numbering: "1.")
#set text(region: "GB")

#show: article.with(
  title: "Primer Scheme Specifications",
  authors: (
    "Chris Kent": author-meta(
      "UOB",
      email: "chrisgkent@protonmail.com",
      orcid: "1234"
    ),
    "Bede Constantinides": author-meta(
      "UOB",
    ),
  ),
  affiliations: (
    "UOB": "Institute of Microbiology and Infection, University of Birmingham, Birmingham, UK.",
  ),
  abstract: [Amplicon Sequencing has become a dominant method for genomic surveillance. However, the lack of defined file format has lead to incompatibility issues with downstream analysis, and constantly evolving formats. Here we describe a universal specification for the primer.bed and the corresponding reference.fasta files, which will aid compatibility.  ],
  keywords: ("Data standards", "Primer Schemes", "Amplicon Sequencing")
)

#outline()

= primer.bed file
A primer.bed file describes an amplicon sequencing primer scheme and is generated by tooling. Its purpose is to encapsulate all the information needed to i) reproduce a primer scheme and ii) facilitate correct bioinformatic analysis of resulting sequencing data. It therefore incorporates both wet lab and analytical elements. These include primer sequences, their associated pools, and relative concentrations, as well as their coordinates with respect to one or more reference genome sequences.

== Format overview 

`primer.bed` files are tab-delimited text files. Lines prefixed with  Each line can either be a `comment line` (prefixed with #highlight[`#`]) or a `BedLine`, which represents a single unique primer (Oligonucleotide) that forms part of an associated amplicon. A compliant `primer.bed` file contains one or more amplicons. 

The format of `primer.bed` is based on the Browser Extensible Data (#link("https://samtools.github.io/hts-specs/BEDv1.pdf")[BED]) specification, with seven required columns followed by one optional column.

== Comment Line

The comment line is minimally parsed, but has the option to contain #highlight[`key=value`] pairs. If the line contains a single #highlight[`=`] it will be split, with the #highlight[`left|right`] sides being #highlight[`key|value`] respectively. 

== BedLine field descriptions 

#figure(
table(
  columns: 5,
  align: (left, left, left, left, right),
    table.header[*Column*][*Field Name*][*Type*][*Brief description*][*Restrictions*],
    [1], [chrom], [String], [Chromosome name], [`[A-Za-z0-9_]`],
    [2], [primerStart], [Int], [Primer start position], [`u64`],
    [3], [primerEnd], [Int], [Primer end position], [`u64`],
    [4], [primerName], [String], [Primer name], [`[a-zA-Z0-9\-]+_[0-9]+_(LEFT|RIGHT)_[0-9]+`],
    [5], [pool], [Int], [Primer pool], [`u64`],
    [6], [strand], [String], [Primer strand], [`[-+]`],
    [7], [primerSeq], [Optional(float)], [Primer weight for PCR reactions], [`f64` > 0 ],
    [8], [attributes], [String], [list of `key=value` pairs separated by \`;\`], [`f64` > 0 ]
  ),
caption: [The column structure and description of a BedLine])


=== #highlight[`chrom`]
The name of the corresponding reference sequence chromosome for the primer. This must match a valid sequence ID inside an accompanying reference sequence FASTA file,  by convention named `reference.fasta`.

=== #highlight[`primerStart`]
The start position of the primer on the `chrom`.

=== #highlight[`primerEnd`]
The non-inclusive end position of the primer on the `chrom`. Must be greater than #highlight[`primerStart`].

=== #highlight[`primerName`]
The name of the primer in the form "`{prefix}_{ampliconNumber}_{direction}_{primerNumber}`". 
    - #highlight[`prefix`]: Must match regex `[a-zA-Z0-9\-]`. See best practices
    - #highlight[`ampliconNumber`]: The number of the amplicon for its relevant #highlight[`chrom`]. Must be a positive integer incrementing from 1.
    - #highlight[`direction`]: The direction of the primers. Must be either `LEFT` or `RIGHT`.
    - #highlight[`primerNumber`]: The number of the primer. Must be a positive integer incrementing from 1.
    
=== #highlight[`pool`]
The PCR pool the primer belongs to. Must be a positive integer incrementing from 1.

=== #highlight[`strand`]
The strand of the primer. Must be either #highlight[`+`] or #highlight[`-`]. Required to match the `primerName:direction` (`LEFT`==`+`, `RIGHT`==`-`)

=== #highlight[`primerSeq`]
The sequence of the primer in the 5' to 3' direction. Unrestricted to contain any character #footnote["This is unrestricted (rather than IUPAC-only) to allow Primer Modification. Such as `/56-FAM/{primerSeq}` to represent 5' 6-FAM  fluorescent dye labeled primer"], and parsed by only removing white space.

=== #highlight[`primerAttributes`]
An *optional* list of a #highlight[`key=value`] pair to denote additional primer attributes, in the form of #highlight[`pw=1.0;ps=10.0`]. This is intentionally flexible to allow the storage of additional information. 

Some key are reserved and undergo validation;
- #highlight[`pw|primerWeight`]: To ensure all amplicons perform similarly, the concentration of individual primers can be altered. Primer Concentration in the PCR should be scaled by `primerWeight * [typical PCR conc]`. This is restricted to positive numerics (`f64 > 0`).  


== Examples

=== Simple example
A seven column #highlight[`primer.bed`] file, with no #highlight[`primerAttributes`] or `comment lines`.

#block(
  fill: luma(230),
  inset: 8pt,
  radius: 2pt,
```
MN908947.3	100 131	example_1_LEFT_1	1	+	CTCTTGTAGATCTGTTCTCTAAACGAACTTT
MN908947.3	419	447	example_1_RIGHT_1	1	-	AAAACGCCTTTTTCAACTTCTACTAAGC
MN908947.3	344	366	example_2_LEFT_1	2	+	TCGTACGTGGCTTTGGAGACTC
MN908947.3	707	732	example_2_RIGHT_1	2	-	TCTTCATAAGGATCAGTGCCAAGCT
```
)

=== Complex example
An eight column #highlight[`primer.bed`] file. With #highlight[`primerAttributes`] defined, and `comment lines` providing a #highlight[`chrom`] alias and explaining the #highlight[`gc`] #highlight[`primerAttributes`].
#block(
  fill: luma(230),
  inset: 8pt,
  radius: 2pt,
  [ #show raw: set text(size: 8pt)
```
# example scheme
# gc=fraction gc
# MN908947.3=sars-cov-2
MN908947.3	100 131	example_1_LEFT_1	1	+	CTCTTGTAGATCTGTTCTCTAAACGAACTTT pw=1.4;gc=0.35
MN908947.3	419	447	example_1_RIGHT_1	1	-	AAAACGCCTTTTTCAACTTCTACTAAGC  pw=1.4;gc=0.36
MN908947.3	344	366	example_2_LEFT_1	2	+	TCGTACGTGGCTTTGGAGACTC  pw=1;gc=0.55
MN908947.3	707	732	example_2_RIGHT_1	2	-	TCTTCATAAGGATCAGTGCCAAGCT pw=1;gc=0.44
```])

== Best Practices

`primer.bed` contain information about how to replicate the primer pools used in multiplexed PCR. They do not contain information about the PCR protocol, input material, or sequencing method and analysis. Therefore, additional information is needed for true reproducibility. 

=== Other metadata standards

To explicitly differentiate different versions of #highlight[`primer.bed`], this spec is designed to fit into larger metadata standards, such as #link("https://github.com/ChrisgKent/primal-page")[primal-page] with #link("https://labs.primalscheme.com")[PrimalScheme Labs] or #link("https://github.com/pha4ge/primaschema")[primaschema] with #link("https://github.com/pha4ge/primer-schemes")[pha4ge primer-schemes]

=== Other tooling

#link("https://github.com/ChrisgKent/primalbedtools")[`primalbedtools`] is a python package that carries out schema validation and conversion, and common operations on #highlight[`primer.bed`] files. 

=== #highlight[`primerName:prefix`]
The #highlight[`primerName:prefix`] should be as unique as possible (ideally a short uuid. For example #highlight[`359ba5`]) and different for #highlight[`chrom`] and the scheme generation run. 
- Using #highlight[`primerName:prefix`] like #highlight[`scheme`] or #highlight[`sars-cov-2`] might seen easier, however, will result in a freezer / LIMS full of simular names leading to pooling mistakes.

=== comment line

The `comment line`'s #highlight[`key=value`] pattern is non-validated and should be non-critical to the bed file function. Although it is recommended that is it used to explained non-standard #highlight[`primerAttributes`]. 

Another use is providing aliases for different #highlight[`chrom`].


= reference.fasta file 
A #highlight[`reference.fasta`] file contains the DNA sequences of all the primary-reference genomes, used in primerscheme generation. Its purpose is to provide a reference genome, and coordinate system to be used for referenced-based assembly and consensus generation.

== Format overview  

#highlight[`reference.fasta`] files are typical #highlight[`.fasta`] #link("https://en.wikipedia.org/wiki/FASTA_format")[format files], with text representing the nucleotide sequence of the reference. Each genome starts with a header line (starting with #highlight[`>`]) that denotes the id of the genome, followed by lines of nucleotide data. 

All #highlight[`chrom`] fields of the BedLines must have a corresponding id in the #highlight[`reference.fasta`].


== Examples

=== Single fasta

#block(
  fill: luma(230),
  inset: 8pt,
  radius: 2pt,
  [ #show raw: set text(size: 8pt)
```
>MN908947.3
ATTAAAGGTTTATACCTTCCCA...
```
])

> The corresponding #highlight[`primer.bed`] file should contain the #highlight[`chrom`] #highlight[`MN908947.3`]

 === Multi fasta
#block(
  fill: luma(230),
  inset: 8pt,
  radius: 2pt,
  [ #show raw: set text(size: 8pt)
```
>MN908947.3
ATTAAAGGTTTATACCTTCCCA...
>NC_006432.1
CGGACACACAAAAAGAAAGAAA...
``` 
])

> The corresponding #highlight[`primer.bed`] file should contain the #highlight[`chrom`] #highlight[`MN908947.3`] and #highlight[`NC_006432.1`]


== Best practices 

As the `reference.fasta` is often used for referenced-based assembly, using high quality genome with minimal `Ns` or ambiguous bases is advisable.  Using RNA sequences in the `reference.fasta` is not advice, as DNA is expected.
